### ISSUE TITLE
in conjunction with nova-sortable

### ISSUE THREAD

**Issue by Brand3000** [trin4ik/nova-switcher#6] opened 2023-07-27 20:07 UTC
Hi! I use your package in conjunction with https://github.com/outl1ne/nova-sortable and it doesn't work properly.
If you try this package, you will see the problem. I have fixed it by adding this.value = this.field.value; in the label method. 
If you have time and agree with my correction. it'd be great to fix that in your package.
Thanks.

**Comment by Johan-An** [comment] 2023-10-20 06:48
I have some question. Hope it get fixed as soon as possible.

**Comment by trin4ik** [comment] 2023-10-20 10:37
@Johan-An @Brand3000 can u show your composer.json and model config (sortable level)? 
i make blank project with [nova-sortable](https://github.com/outl1ne/nova-sortable) and [nova-switcher](https://github.com/trin4ik/nova-switcher) and i dont have a problem.

![Peek 2023-10-20 13-31](https://github.com/trin4ik/nova-switcher/assets/839633/f41475c1-7137-4b3f-a2df-5d1dfec60c44)

composer.json:
```json
{
    "require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/nova": "^4.24",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "outl1ne/nova-sortable": "^3.4",
        "spatie/eloquent-sortable": "^4.0",
        "trin4ik/nova-switcher": "^0.3.0"
    }
}
```
Models/User.php:
```php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\EloquentSortable\SortableTrait;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;
    use SortableTrait;

    public $sortable = [
        'order_column_name' => 'order_column',
        'sort_when_creating' => true,
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}
```
Nova/User.php
```php
<?php

namespace App\Nova;

use Illuminate\Http\Request;
use Illuminate\Validation\Rules;
use Laravel\Nova\Fields\Gravatar;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Password;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Http\Requests\NovaRequest;
use Outl1ne\NovaSortable\Traits\HasSortableRows;
use Trin4ik\NovaSwitcher\NovaSwitcher;

class User extends Resource
{
    use HasSortableRows;

    /**
     * The model the resource corresponds to.
     *
     * @var class-string<\App\Models\User>
     */
    public static $model = \App\Models\User::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'name';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id', 'name', 'email',
    ];

    /**
     * Get the fields displayed by the resource.
     *
     * @param \Laravel\Nova\Http\Requests\NovaRequest $request
     * @return array
     */
    public function fields (NovaRequest $request)
    {
        return [
            ID::make()->sortable(),

            Gravatar::make()->maxWidth(50),

            Text::make('Name')
                ->sortable()
                ->rules('required', 'max:255'),

            Text::make('Email')
                ->sortable()
                ->rules('required', 'email', 'max:254')
                ->creationRules('unique:users,email')
                ->updateRules('unique:users,email,{{resourceId}}'),

            Password::make('Password')
                ->onlyOnForms()
                ->creationRules('required', Rules\Password::defaults())
                ->updateRules('nullable', Rules\Password::defaults()),

            NovaSwitcher::make('Active', 'disabled')
                ->reverse()
        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param \Laravel\Nova\Http\Requests\NovaRequest $request
     * @return array
     */
    public function cards (NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @param \Laravel\Nova\Http\Requests\NovaRequest $request
     * @return array
     */
    public function filters (NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @param \Laravel\Nova\Http\Requests\NovaRequest $request
     * @return array
     */
    public function lenses (NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @param \Laravel\Nova\Http\Requests\NovaRequest $request
     * @return array
     */
    public function actions (NovaRequest $request)
    {
        return [];
    }
}
```

**Comment by Brand3000** [comment] 2023-10-21 09:50
You change checkboxes for both records in your movie, and it doesn't help to see the problem. On the index page change a checkbox only for one record to see different statuses and it will do the trick

**Comment by Johan-An** [comment] 2023-10-23 09:55
composer.json
{
"require": {&nbsp; &nbsp; &nbsp; &nbsp; "php": "^8.1",
&nbsp; &nbsp; &nbsp; &nbsp; "laravel/framework": "^10.10",
&nbsp; &nbsp; &nbsp; &nbsp; "laravel/nova": "^4.0",
&nbsp; &nbsp; &nbsp; &nbsp; "outl1ne/nova-sortable": "^3.4",
&nbsp; &nbsp; &nbsp; &nbsp; "trin4ik/nova-switcher": "^0.3.0",
&nbsp; &nbsp; }

}





Villagelover
***@***.***







                       
Original Email
                       
                     

Sender:"trin4ik"< ***@***.*** &gt;;

Sent Time:2023/10/20 18:37

To:"trin4ik/nova-switcher"< ***@***.*** &gt;;

Cc recipient:"Johan An"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

Subject:Re: [trin4ik/nova-switcher] in conjunction with nova-sortable (Issue#6)




 
@Johan-An @Brand3000 can u show your composer.json and model config (sortable level)?
 i make blank project with nova-sortable and nova-switcher and i dont have a problem.
 

 
composer.json:
 {     "require": {         "php": "^8.1",         "guzzlehttp/guzzle": "^7.2",         "laravel/framework": "^10.10",         "laravel/nova": "^4.24",         "laravel/sanctum": "^3.2",         "laravel/tinker": "^2.8",         "outl1ne/nova-sortable": "^3.4",         "spatie/eloquent-sortable": "^4.0",         "trin4ik/nova-switcher": "^0.3.0"     } }
 
Models/User.php:
 <?php namespace App\Models; // use Illuminate\Contracts\Auth\MustVerifyEmail; use Illuminate\Database\Eloquent\Factories\HasFactory; use Illuminate\Foundation\Auth\User as Authenticatable; use Illuminate\Notifications\Notifiable; use Laravel\Sanctum\HasApiTokens; use Spatie\EloquentSortable\SortableTrait; class User extends Authenticatable {     use HasApiTokens, HasFactory, Notifiable;     use SortableTrait;     public $sortable = [         'order_column_name' =&gt; 'order_column',         'sort_when_creating' =&gt; true,     ];     /**      * The attributes that are mass assignable.      *      * @var array<int, string&gt;      */     protected $fillable = [         'name',         'email',         'password',     ];     /**      * The attributes that should be hidden for serialization.      *      * @var array<int, string&gt;      */     protected $hidden = [         'password',         'remember_token',     ];     /**      * The attributes that should be cast.      *      * @var array<string, string&gt;      */     protected $casts = [         'email_verified_at' =&gt; 'datetime',         'password' =&gt; 'hashed',     ]; }
 
Nova/User.php
 <?php namespace App\Nova; use Illuminate\Http\Request; use Illuminate\Validation\Rules; use Laravel\Nova\Fields\Gravatar; use Laravel\Nova\Fields\ID; use Laravel\Nova\Fields\Password; use Laravel\Nova\Fields\Text; use Laravel\Nova\Http\Requests\NovaRequest; use Outl1ne\NovaSortable\Traits\HasSortableRows; use Trin4ik\NovaSwitcher\NovaSwitcher; class User extends Resource {     use HasSortableRows;     /**      * The model the resource corresponds to.      *      * @var class-string<\App\Models\User&gt;      */     public static $model = \App\Models\User::class;     /**      * The single value that should be used to represent the resource when being displayed.      *      * @var string      */     public static $title = 'name';     /**      * The columns that should be searched.      *      * @var array      */     public static $search = [         'id', 'name', 'email',     ];     /**      * Get the fields displayed by the resource.      *      * @param \Laravel\Nova\Http\Requests\NovaRequest $request      * @return array      */     public function fields (NovaRequest $request)     {         return [             ID::make()-&gt;sortable(),             Gravatar::make()-&gt;maxWidth(50),             Text::make('Name')                 -&gt;sortable()                 -&gt;rules('required', 'max:255'),             Text::make('Email')                 -&gt;sortable()                 -&gt;rules('required', 'email', 'max:254')                 -&gt;creationRules('unique:users,email')                 -&gt;updateRules('unique:users,email,{{resourceId}}'),             Password::make('Password')                 -&gt;onlyOnForms()                 -&gt;creationRules('required', Rules\Password::defaults())                 -&gt;updateRules('nullable', Rules\Password::defaults()),             NovaSwitcher::make('Active', 'disabled')                 -&gt;reverse()         ];     }     /**      * Get the cards available for the request.      *      * @param \Laravel\Nova\Http\Requests\NovaRequest $request      * @return array      */     public function cards (NovaRequest $request)     {         return [];     }     /**      * Get the filters available for the resource.      *      * @param \Laravel\Nova\Http\Requests\NovaRequest $request      * @return array      */     public function filters (NovaRequest $request)     {         return [];     }     /**      * Get the lenses available for the resource.      *      * @param \Laravel\Nova\Http\Requests\NovaRequest $request      * @return array      */     public function lenses (NovaRequest $request)     {         return [];     }     /**      * Get the actions available for the resource.      *      * @param \Laravel\Nova\Http\Requests\NovaRequest $request      * @return array      */     public function actions (NovaRequest $request)     {         return [];     } }

**Comment by Johan-An** [comment] 2023-10-23 10:01
![example](https://github.com/trin4ik/nova-switcher/assets/23259415/7c4903de-1567-4d81-a28a-74fef26918fa)
![image](https://github.com/trin4ik/nova-switcher/assets/23259415/bdfb4e51-1985-4fd5-91ba-b6e6730733e6)

![image](https://github.com/trin4ik/nova-switcher/assets/23259415/a94143e4-32a0-4188-a48c-6c0c9c2ed2c7)
composer.json
{
"require": {
        "php": "^8.1",
        "laravel/framework": "^10.10",
        "laravel/nova": "^4.0",
        "mobilenowgroup/laravel-dingding-notification": "^1.0",
        "mobilenowgroup/laravel-nova-preview-component-package": "^1.0",
        "outl1ne/nova-sortable": "^3.4",
        "stepanenko3/nova-command-runner": "^4.2",
        "trin4ik/nova-switcher": "^0.3.0",
    }
}

**Comment by trin4ik** [comment] 2023-10-26 07:42
@Johan-An I don't understand what this has to do with switcher.
What version is your nova? 

![Peek 2023-10-26 10-40](https://github.com/trin4ik/nova-switcher/assets/839633/9df067c7-c050-428c-9e92-71ed137c18a0)

**Comment by Johan-An** [comment] 2023-10-26 08:23
> @Johan-An I don't understand what this has to do with switcher. What version is your nova?
> 
> ![Peek 2023-10-26 10-40](https://user-images.githubusercontent.com/839633/278251029-9df067c7-c050-428c-9e92-71ed137c18a0.gif) [ ![Peek 2023-10-26 10-40](https://user-images.githubusercontent.com/839633/278251029-9df067c7-c050-428c-9e92-71ed137c18a0.gif) ](https://user-images.githubusercontent.com/839633/278251029-9df067c7-c050-428c-9e92-71ed137c18a0.gif) [ ](https://user-images.githubusercontent.com/839633/278251029-9df067c7-c050-428c-9e92-71ed137c18a0.gif)

![image](https://github.com/trin4ik/nova-switcher/assets/23259415/7bd192fb-bf2f-4ce1-b433-4dcfe8e84e3a)

**Comment by Johan-An** [comment] 2023-10-26 08:25
> @Johan-An I don't understand what this has to do with switcher. What version is your nova?
> 


![image](https://github.com/trin4ik/nova-switcher/assets/23259415/55404114-3fd3-4fa9-893f-4df493795413)

**Comment by Johan-An** [comment] 2023-10-26 08:44
FYI：
app/Models/FaqSubject.php
```php
<?php

namespace App\Models;

use App\Models\Traits\PublishAble;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\EloquentSortable\Sortable;
use Spatie\EloquentSortable\SortableTrait;

class FaqSubject extends Model implements Sortable
{
    use HasFactory, PublishAble, SortableTrait;

    const HORSE_RIDING_CATE_SLUG = 'horse_riding';

    const FOOTBALL_CATE_SLUG = 'football';

    const MULTI_SPORTS_CATE_SLUG = 'multi_sports';

    /**
     * @var array
     */
    public $sortable = [
        'order_column_name' => 'sort',
        'sort_when_creating' => false,
        'nova_order_by' => 'ASC',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function faqs()
    {
        return $this->hasMany(Faq::class);
    }

    /**
     * @return array
     */
    public static function getCateSlug()
    {
        return [
            self::HORSE_RIDING_CATE_SLUG => __('Horse Riding'),
            self::FOOTBALL_CATE_SLUG => __('Football'),
            self::MULTI_SPORTS_CATE_SLUG => __('Multi Sports'),
        ];
    }

    public function scopeFilterForApi(Builder $query)
    {
        $query->has('faqs')->with('faqs');

        if ($cate = request()->input('cate_slug')) {
            return $query->where('cate_slug', $cate);
        }

        return $query;
    }
}

``` 
app/Nova/FaqSubject.php
```php
<?php

namespace App\Nova;

use Laravel\Nova\Fields\Badge;
use Laravel\Nova\Fields\HasMany;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Select;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Http\Requests\NovaRequest;
use Outl1ne\NovaSortable\Traits\HasSortableManyToManyRows;
use Outl1ne\NovaSortable\Traits\HasSortableRows;
use Trin4ik\NovaSwitcher\NovaSwitcher;

class FaqSubject extends Resource
{
    use HasSortableManyToManyRows, HasSortableRows;

    /**
     * The model the resource corresponds to.
     *
     * @var class-string<\App\Models\FaqSubject>
     */
    public static $model = \App\Models\FaqSubject::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'title';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id',
        'title',
    ];

    /**
     * Get the fields displayed by the resource.
     *
     * @return array
     */
    public function fields(NovaRequest $request)
    {
        return [
            ID::make()->sortable(),

            Text::make(__('Theme'), 'title')
                ->rules('required'),

            Select::make(__('Category'), 'cate_slug')
                ->rules('required')
                ->displayUsingLabels()
                ->filterable()
                ->options(\App\Models\FaqSubject::getCateSlug()),

            NovaSwitcher::make(__('Published'), 'status'),

            HasMany::make(__('Faq'), 'faqs', Faq::class),
        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @return array
     */
    public function cards(NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @return array
     */
    public function filters(NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @return array
     */
    public function lenses(NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @return array
     */
    public function actions(NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the displayable label of the resource.
     *
     * @return string
     */
    public static function label()
    {
        return __('Themes');
    }

    /**
     * Get the displayable singular label of the resource.
     *
     * @return string
     */
    public static function singularLabel()
    {
        return __('theme');
    }
}

```

**Comment by trin4ik** [comment] 2023-10-26 14:32
@Johan-An i still ok (( 
Can you publish small laravel project with minimal functionality, where hava this bug?
I want to help, but I can't see the problem.

**Comment by Johan-An** [comment] 2023-10-27 04:14
![laravel10](https://github.com/trin4ik/nova-switcher/assets/23259415/1c0d0a44-dc00-4c0a-a437-ac8b2d41bc8d)

Sure. Please refer to this: https://github.com/Johan-An/laravel10

**Comment by trin4ik** [comment] 2023-10-27 10:10
@Johan-An i think, problem with nova version. I don't have any other ideas. try to find 4.28 trial

![Peek 2023-10-27 13-09](https://github.com/trin4ik/nova-switcher/assets/839633/0817125f-3433-44f9-b9fb-5992fa110073)

**Comment by Brand3000** [comment] 2023-10-28 19:56
I'm starting a new project and I've already installed and everything seems to be working fine without amendments.

**Comment by trin4ik** [comment] 2023-10-29 12:15
@Brand3000 TY
@Johan-An I have installed 4.28 and everything is fine. I think the problem is with your version of nova. I see that you have a different refresh animation.

I'm closing this task, but i`m ready to help if we clarify the data

**Closed as completed by trin4ik** 2023-10-29 12:15 UTC

**Comment by Johan-An** [comment] 2023-10-30 02:10
> @Brand3000 TY @Johan-An I have installed 4.28 and everything is fine. I think the problem is with your version of nova. I see that you have a different refresh animation.
> 
> I'm closing this task, but i`m ready to help if we clarify the data

 I'll try to upgrade the nova version next. Thanks for your time sincerely.
